In [33]:
import numpy as np
np

<module 'numpy' from '/Users/tobiahrex/Library/Caches/pypoetry/virtualenvs/learn-ml-KZ9U3PtV-py3.12/lib/python3.12/site-packages/numpy/__init__.py'>

In [41]:
ones_1_3 = np.ones((1, 3), dtype=np.float32)
ones_3_1 = np.ones((3, 1), dtype=np.float32)
ones_3_1

array([[1.],
       [1.],
       [1.]], dtype=float32)

In [38]:
mat_3_3 = np.mat([[1, 1, 1], [2, 2, 2], [3, 3, 3]], dtype=np.float32)
mat_3_3

matrix([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]], dtype=float32)

In [48]:
ones_3_1.dot(ones_1_3) == np.dot(ones_3_1, ones_1_3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [49]:
np.matmul(ones_3_1, ones_1_3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [56]:
vector = np.random.rand(1, 3).transpose()
vector

array([[0.85840039],
       [0.38383582],
       [0.6444935 ]])

In [57]:
np.matmul(vector, ones_1_3)

array([[0.85840039, 0.85840039, 0.85840039],
       [0.38383582, 0.38383582, 0.38383582],
       [0.6444935 , 0.6444935 , 0.6444935 ]])